fixed gh-pahes workflow

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -30,11 +30,20 @@ jobs:
         uses: actions/checkout@v4
       - name: Setup Pages
         uses: actions/configure-pages@v5
-      - name: Build with Jekyll
-        uses: actions/jekyll-build-pages@v1
-        with:
-          source: ./
-          destination: ./_site
+      - name: Find ontology file
+        run: |
+          ONTOLOGY_FILE=$(find src/ontology/ -name "*-full.owl" -type f | head -1)
+          if [ -z "$ONTOLOGY_FILE" ]; then
+            echo "Error: No *-full.owl file found in src/ontology/ directory!"
+            exit 1
+          fi
+          echo "Found ontology file: $ONTOLOGY_FILE"
+          echo "ONTOLOGY_FILE=$ONTOLOGY_FILE" >> $GITHUB_ENV
+      - name: Build HTML for main
+        run: |
+          wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.25/widoco-1.4.25-jar-with-dependencies_JDK-11.jar
+          mkdir ./_site
+          java -jar widoco.jar -ontFile ${{ env.ONTOLOGY_FILE }} -outFolder ./_site  -uniteSections -includeAnnotationProperties -lang en-de  -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl           
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
 
